version: '3.9'
services:
  scrapperdb:
    image: postgres:latest
    container_name: scrapperdb
    restart: always
    healthcheck:
      test: [ "CMD", "pg_is_ready" ]
      timeout: 15s
      interval: 5s
      retries: 10
    environment:
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "scraper"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile_BE
    ports:
      - "8000:8000"
    depends_on:
      - scrapperdb
    links:
      - scrapperdb
    restart: on-failure
  react_app:
    build:
      context: .
      dockerfile: Dockerfile_FE
    ports:
      - "3000:3000"
    depends_on:
      - scrapper
    links:
      - scrapper
    